apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  nodeSelector: 
    node: master
  containers:
  - name: be
    image: "tconguler/check-k8s-cert"
    resources:
    volumeMounts:
    - name: pki
      mountPath: /etc/kubernetes/pki
    - name: nginx
      mountPath: /var/cert
  - name: fe
    image: nginx
    resources:
    volumeMounts:
    - name: nginx
      mountPath: /usr/share/nginx/html
  volumes:
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki
    - name: nginx
      emptyDir: {}